services:
  app_proxy:
    depends_on:
      - web
    environment:
      APP_HOST: web
      APP_PORT: 8000

  db:
    image: postgres:16
    environment:
      POSTGRES_DB: inventree
      POSTGRES_USER: inventree
      POSTGRES_PASSWORD: change-me
    volumes:
      - ${APP_DATA_DIR}/postgres:/var/lib/postgresql/data
    restart: unless-stopped

  cache:
    image: redis:7-alpine
    restart: unless-stopped

  web:
    image: inventree/inventree:stable
    depends_on: [db, cache]
    environment:
      INVENTREE_DB_ENGINE: postgresql
      INVENTREE_DB_HOST: db
      INVENTREE_DB_NAME: inventree
      INVENTREE_DB_USER: inventree
      INVENTREE_DB_PASSWORD: change-me
      INVENTREE_CACHE_HOST: cache
      INVENTREE_CACHE_PORT: "6379"
      # >>> Fix B unten (SITE_URL) kommt hierhin <<<
    volumes:
      - ${APP_DATA_DIR}/inventree-data:/home/inventree/data
    restart: unless-stopped

  worker:
    image: inventree/inventree:stable
    command: invoke worker
    depends_on: [web]
    environment:
      INVENTREE_DB_ENGINE: postgresql
      INVENTREE_DB_HOST: db
      INVENTREE_DB_NAME: inventree
      INVENTREE_DB_USER: inventree
      INVENTREE_DB_PASSWORD: change-me
      INVENTREE_CACHE_HOST: cache
      INVENTREE_CACHE_PORT: "6379"
      # >>> Fix B unten (SITE_URL) kommt hierhin <<<
    volumes:
      - ${APP_DATA_DIR}/inventree-data:/home/inventree/data
    restart: unless-stopped
