services:
  app_proxy:
    environment:
      APP_HOST: verdox-pc-inventory_app_1
      APP_PORT: 8080
      APP_PROTOCOL: http
    restart: on-failure

  db:
    image: postgres:16-alpine
    restart: on-failure
    environment:
      POSTGRES_DB: pcparts
      POSTGRES_USER: pcparts
      POSTGRES_PASSWORD: pcparts
    volumes:
      - ${APP_DATA_DIR}/postgres:/var/lib/postgresql/data

  app:
    image: verdox/hardware-inventar-system:latest
    depends_on:
      - db
    restart: on-failure
    user: "0:1000"
    environment:
      SERVER_PORT: 8080         # Spring lauscht auf 0.0.0.0:8080
      SPRING_PROFILES_ACTIVE: prod
      SPRING_DATASOURCE_URL: jdbc:postgresql://db:5432/pcparts
      SPRING_DATASOURCE_USERNAME: pcparts
      SPRING_DATASOURCE_PASSWORD: pcparts
      SELENIUM_REMOTE_URL: http://selenium:4444/wd/hub
      # Optional hilfreich hinter Proxy:
      # SERVER_FORWARD_HEADERS_STRATEGY: framework
    volumes:
      - ${APP_DATA_DIR}/data:/data

  selenium:
    image: selenium/standalone-all-browsers:latest
    shm_size: 2g
    ports:
      - "4444:4444"   # WebDriver
    volumes:
      - ${APP_DATA_DIR}/chrome-profile:/home/seluser/profile
    environment:
      - SE_NODE_MAX_SESSIONS=16
