services:
  app_proxy:
    environment:
      APP_HOST: verdox-pc-inventory_app_1
      APP_PORT: 8080
      APP_PROTOCOL: http
    restart: on-failure

  db:
    image: postgres:16-alpine
    restart: on-failure
    environment:
      POSTGRES_DB: pcparts
      POSTGRES_USER: pcparts
      POSTGRES_PASSWORD: pcparts
    volumes:
      - ${APP_DATA_DIR}/db-data:/var/lib/postgresql/data

  app:
    image: verdox/hardware-inventar-system:latest
    depends_on:
      - db
    restart: on-failure
    user: "0:1000"
    environment:
      SERVER_PORT: 8080         # Spring lauscht auf 0.0.0.0:8080
      SPRING_PROFILES_ACTIVE: prod
      SPRING_DATASOURCE_URL: jdbc:postgresql://db:5432/pcparts?currentSchema=pcparts
      SPRING_DATASOURCE_USERNAME: pcparts
      SPRING_DATASOURCE_PASSWORD: pcparts
      SELENIUM_REMOTE_URL: http://selenium:4444/wd/hub
      OPEN_HARDWARE_API_ENDPOINT: http://verdox-open-hardware-api_app_1:8085
      # Optional hilfreich hinter Proxy:
      # SERVER_FORWARD_HEADERS_STRATEGY: framework
    volumes:
      - ${APP_DATA_DIR}:/var/lib/pc-storage-system
