services:
  app_proxy:
    environment:
      APP_HOST: verdox-open-hardware-api_app_1
      APP_PORT: 5050
      APP_PROTOCOL: http
      PROXY_AUTH_ADD: "false"
    restart: on-failure

  db:
    image: postgres:16-alpine
    restart: on-failure
    environment:
      POSTGRES_DB: pcparts
      POSTGRES_USER: pcparts
      POSTGRES_PASSWORD: pcparts
    volumes:
      - ${APP_DATA_DIR}/db-data:/var/lib/postgresql/data

  app:
    image: verdox/open-hardware-api:latest
    depends_on:
      - db
      - selenium
    restart: on-failure
    user: "0:1000"
    environment:
      SERVER_PORT: 5050
      SPRING_PROFILES_ACTIVE: prod
      SPRING_DATASOURCE_URL: jdbc:postgresql://db:5432/pcparts?currentSchema=openhwapi
      SPRING_DATASOURCE_USERNAME: pcparts
      SPRING_DATASOURCE_PASSWORD: pcparts
      SELENIUM_REMOTE_URL: http://selenium:4444/wd/hub
    networks:
      default:
        ipv4_address: ${APP_OPENHW_API_IP}
    volumes:
      - ${APP_DATA_DIR}:/var/lib/open-hardware-api

  selenium:
    image: selenium/standalone-all-browsers:latest
    shm_size: 2g
    ports:
      - "4444:4444"   # WebDriver
    volumes:
      - ${APP_DATA_DIR}/chrome-profile:/home/seluser/profile
    environment:
      - SE_NODE_MAX_SESSIONS=16

networks:
  default:
    external: true
    name: umbrel_main_network
