# Docker compose recipe for a production-ready InvenTree setup
# Source: https://docs.inventree.org/en/stable/start/docker_install/ (contrib/container/docker-compose.yml)
# You typically should not edit this file. Adjust settings in .env instead.

services:
  # PostgreSQL database backend
  inventree-db:
    image: postgres:17
    container_name: inventree-db
    expose:
      - ${INVENTREE_DB_PORT:-5432}/tcp
    environment:
      - PGDATA=/var/lib/postgresql/data/pgdb
      - POSTGRES_USER=${INVENTREE_DB_USER:?You must provide the 'INVENTREE_DB_USER' variable in the .env file}
      - POSTGRES_PASSWORD=${INVENTREE_DB_PASSWORD:?You must provide the 'INVENTREE_DB_PASSWORD' variable in the .env file}
      - POSTGRES_DB=${INVENTREE_DB_NAME:?You must provide the 'INVENTREE_DB_NAME' variable in the .env file}
    volumes:
      # Map 'data' volume so Postgres database is stored externally
      - ${INVENTREE_EXT_VOLUME:?You must specify the 'INVENTREE_EXT_VOLUME' variable in the .env file!}:/var/lib/postgresql/data/:z
    restart: unless-stopped

  # Redis cache
  inventree-cache:
    image: redis:7-alpine
    container_name: inventree-cache
    env_file:
      - .env
    expose:
      - ${INVENTREE_CACHE_PORT:-6379}
    restart: always

  # InvenTree web server (gunicorn)
  inventree-server:
    image: inventree/inventree:${INVENTREE_TAG:-stable}
    container_name: inventree-server
    expose:
      - 8000
    depends_on:
      - inventree-db
      - inventree-cache
    env_file:
      - .env
    volumes:
      # Data volume must map to /home/inventree/data
      - ${INVENTREE_EXT_VOLUME}:/home/inventree/data:z
    restart: unless-stopped

  # Background worker (django-q)
  inventree-worker:
    image: inventree/inventree:${INVENTREE_TAG:-stable}
    container_name: inventree-worker
    command: invoke worker
    depends_on:
      - inventree-server
    env_file:
      - .env
    volumes:
      - ${INVENTREE_EXT_VOLUME}:/home/inventree/data:z
    restart: unless-stopped

  # Caddy reverse proxy and static/media server
  inventree-proxy:
    container_name: inventree-proxy
    image: caddy:alpine
    restart: always
    depends_on:
      - inventree-server
    ports:
      # If ports 80/443 are busy on your host, change them (e.g. 8080:80, 8443:443)
      - ${INVENTREE_WEB_PORT:-80}:80
      - 443:443
    env_file:
      - .env
    volumes:
      - ./Caddyfile:/etc/caddy/Caddyfile:ro,z
      - ${INVENTREE_EXT_VOLUME}/static:/var/www/static:z
      - ${INVENTREE_EXT_VOLUME}/media:/var/www/media:z
      - ${INVENTREE_EXT_VOLUME}:/var/log:z
      - ${INVENTREE_EXT_VOLUME}:/data:z
      - ${INVENTREE_EXT_VOLUME}:/config:z
